baseURL = "https://livet.me/"
defaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "Andréas Livet"
theme = "ananke"

[params]
  favicon = ""
  site_logo = ""
  description = "Site d'Andréas Livet (anciennement La Conviviale)"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  custom_css = ["posts.css"]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/chassis_large.jpg"
  recent_posts_number = 2